config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create, :index]
  end
  # resources :reviews, only: [:destroy, :update, :edit, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true

  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { in: 0..5, :only_integer => true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
    # redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit the restaurant <%= @restaurant %></h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>List of Restaurants</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>

</div>

app/views/restaurants/new.html.erb
<h1>Add a new Restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="container">

  <h1><%= @restaurant.name %></h1>
  <p><b><%= @restaurant.category %></b></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>

  <h3>Reviews</h3>

  <ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> <%= review.rating %></li>
    <% end %>
  </ul>

      <h4>Add a new review</h4>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/reviews/show.html.erb
<div class="container">
  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %><%= review.rating %></li>
    <% end %>
  </ul>
  <br>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header"><%= link_to "Restaurants", restaurants_path %></div>
      <div class="navbar-header"><%= link_to "Add a new restaurant", new_restaurant_path %></div>
    </div>
</nav>